# Use official lightweight Python image
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy everything
COPY . .

# Install Flask
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 5001

# Run the Flask app
CMD ["python", "server.py"]
